// Fichier généré automatiquement contenant les chapitres de Sahih al-Bukhari
// Généré le 2025-04-11T12:55:52.900242

import 'package:salaty/models/bukhari_chapter.dart';

// Liste des chapitres de Sahih al-Bukhari
final List<BukhariChapter> bukhariChaptersData = [
  BukhariChapter(
    id: 1,
    englishTitle: "Revelation",
    arabicTitle: "كتاب 1",
    startHadith: 1,
    endHadith: 77,
  ),
  BukhariChapter(
    id: 2,
    englishTitle: "Belief",
    arabicTitle: "كتاب 2",
    startHadith: 78,
    endHadith: 154,
  ),
  BukhariChapter(
    id: 3,
    englishTitle: "Knowledge",
    arabicTitle: "كتاب 3",
    startHadith: 155,
    endHadith: 231,
  ),
  BukhariChapter(
    id: 4,
    englishTitle: "Ablutions (Wudu')",
    arabicTitle: "كتاب 4",
    startHadith: 232,
    endHadith: 308,
  ),
  BukhariChapter(
    id: 5,
    englishTitle: "Bathing (Ghusl)",
    arabicTitle: "كتاب 5",
    startHadith: 309,
    endHadith: 385,
  ),
  BukhariChapter(
    id: 6,
    englishTitle: "Menstrual Periods",
    arabicTitle: "كتاب 6",
    startHadith: 386,
    endHadith: 462,
  ),
  BukhariChapter(
    id: 7,
    englishTitle: "Rubbing hands and feet with dust (Tayammum)",
    arabicTitle: "كتاب 7",
    startHadith: 463,
    endHadith: 539,
  ),
  BukhariChapter(
    id: 8,
    englishTitle: "Prayers (Salat)",
    arabicTitle: "كتاب 8",
    startHadith: 540,
    endHadith: 616,
  ),
  BukhariChapter(
    id: 9,
    englishTitle: "Times of the Prayers",
    arabicTitle: "كتاب 9",
    startHadith: 617,
    endHadith: 693,
  ),
  BukhariChapter(
    id: 10,
    englishTitle: "Call to Prayers (Adhaan)",
    arabicTitle: "كتاب 10",
    startHadith: 694,
    endHadith: 770,
  ),
  BukhariChapter(
    id: 11,
    englishTitle: "Friday Prayer",
    arabicTitle: "كتاب 11",
    startHadith: 771,
    endHadith: 847,
  ),
  BukhariChapter(
    id: 12,
    englishTitle: "Fear Prayer",
    arabicTitle: "كتاب 12",
    startHadith: 848,
    endHadith: 924,
  ),
  BukhariChapter(
    id: 13,
    englishTitle: "The Two Festivals (Eids)",
    arabicTitle: "كتاب 13",
    startHadith: 925,
    endHadith: 1001,
  ),
  BukhariChapter(
    id: 14,
    englishTitle: "Witr Prayer",
    arabicTitle: "كتاب 14",
    startHadith: 1002,
    endHadith: 1078,
  ),
  BukhariChapter(
    id: 15,
    englishTitle: "Invoking Allah for Rain (Istisqaa)",
    arabicTitle: "كتاب 15",
    startHadith: 1079,
    endHadith: 1155,
  ),
  BukhariChapter(
    id: 16,
    englishTitle: "Eclipses",
    arabicTitle: "كتاب 16",
    startHadith: 1156,
    endHadith: 1232,
  ),
  BukhariChapter(
    id: 17,
    englishTitle: "Prostration During Recital of Qur'an",
    arabicTitle: "كتاب 17",
    startHadith: 1233,
    endHadith: 1309,
  ),
  BukhariChapter(
    id: 18,
    englishTitle: "Shortening the Prayers (At-Taqseer)",
    arabicTitle: "كتاب 18",
    startHadith: 1310,
    endHadith: 1386,
  ),
  BukhariChapter(
    id: 19,
    englishTitle: "Prayer at Night (Tahajjud)",
    arabicTitle: "كتاب 19",
    startHadith: 1387,
    endHadith: 1463,
  ),
  BukhariChapter(
    id: 20,
    englishTitle: "Virtues of Prayer at Masjid Makkah and Madinah",
    arabicTitle: "كتاب 20",
    startHadith: 1464,
    endHadith: 1540,
  ),
  BukhariChapter(
    id: 21,
    englishTitle: "Actions while Praying",
    arabicTitle: "كتاب 21",
    startHadith: 1541,
    endHadith: 1617,
  ),
  BukhariChapter(
    id: 22,
    englishTitle: "Forgetfulness in Prayer",
    arabicTitle: "كتاب 22",
    startHadith: 1618,
    endHadith: 1694,
  ),
  BukhariChapter(
    id: 23,
    englishTitle: "Funerals (Al-Janaa'iz)",
    arabicTitle: "كتاب 23",
    startHadith: 1695,
    endHadith: 1771,
  ),
  BukhariChapter(
    id: 24,
    englishTitle: "Obligatory Charity Tax (Zakat)",
    arabicTitle: "كتاب 24",
    startHadith: 1772,
    endHadith: 1848,
  ),
  BukhariChapter(
    id: 25,
    englishTitle: "Hajj (Pilgrimage)",
    arabicTitle: "كتاب 25",
    startHadith: 1849,
    endHadith: 1925,
  ),
  BukhariChapter(
    id: 26,
    englishTitle: "`Umrah (Minor pilgrimage)",
    arabicTitle: "كتاب 26",
    startHadith: 1926,
    endHadith: 2002,
  ),
  BukhariChapter(
    id: 27,
    englishTitle: "Pilgrims Prevented from Completing the Pilgrimage",
    arabicTitle: "كتاب 27",
    startHadith: 2003,
    endHadith: 2079,
  ),
  BukhariChapter(
    id: 28,
    englishTitle: "Penalty of Hunting while on Pilgrimage",
    arabicTitle: "كتاب 28",
    startHadith: 2080,
    endHadith: 2156,
  ),
  BukhariChapter(
    id: 29,
    englishTitle: "Virtues of Madinah",
    arabicTitle: "كتاب 29",
    startHadith: 2157,
    endHadith: 2233,
  ),
  BukhariChapter(
    id: 30,
    englishTitle: "Fasting",
    arabicTitle: "كتاب 30",
    startHadith: 2234,
    endHadith: 2310,
  ),
  BukhariChapter(
    id: 31,
    englishTitle: "Praying at Night in Ramadaan (Taraweeh)",
    arabicTitle: "كتاب 31",
    startHadith: 2311,
    endHadith: 2387,
  ),
  BukhariChapter(
    id: 32,
    englishTitle: "Virtues of the Night of Qadr",
    arabicTitle: "كتاب 32",
    startHadith: 2388,
    endHadith: 2464,
  ),
  BukhariChapter(
    id: 33,
    englishTitle: "Retiring to a Mosque for Remembrance of Allah (I'tikaf)",
    arabicTitle: "كتاب 33",
    startHadith: 2465,
    endHadith: 2541,
  ),
  BukhariChapter(
    id: 34,
    englishTitle: "Sales and Trade",
    arabicTitle: "كتاب 34",
    startHadith: 2542,
    endHadith: 2618,
  ),
  BukhariChapter(
    id: 35,
    englishTitle: "Sales in which a Price is paid for Goods to be Delivered Later (As-Salam)",
    arabicTitle: "كتاب 35",
    startHadith: 2619,
    endHadith: 2695,
  ),
  BukhariChapter(
    id: 36,
    englishTitle: "Shuf'a",
    arabicTitle: "كتاب 36",
    startHadith: 2696,
    endHadith: 2772,
  ),
  BukhariChapter(
    id: 37,
    englishTitle: "Hiring",
    arabicTitle: "كتاب 37",
    startHadith: 2773,
    endHadith: 2849,
  ),
  BukhariChapter(
    id: 38,
    englishTitle: "Transferance of a Debt from One Person to Another (Al-Hawaala)",
    arabicTitle: "كتاب 38",
    startHadith: 2850,
    endHadith: 2926,
  ),
  BukhariChapter(
    id: 39,
    englishTitle: "Kafalah",
    arabicTitle: "كتاب 39",
    startHadith: 2927,
    endHadith: 3003,
  ),
  BukhariChapter(
    id: 40,
    englishTitle: "Representation, Authorization, Business by Proxy",
    arabicTitle: "كتاب 40",
    startHadith: 3004,
    endHadith: 3080,
  ),
  BukhariChapter(
    id: 41,
    englishTitle: "Agriculture",
    arabicTitle: "كتاب 41",
    startHadith: 3081,
    endHadith: 3157,
  ),
  BukhariChapter(
    id: 42,
    englishTitle: "Distribution of Water",
    arabicTitle: "كتاب 42",
    startHadith: 3158,
    endHadith: 3234,
  ),
  BukhariChapter(
    id: 43,
    englishTitle: "Loans, Payment of Loans, Freezing of Property, Bankruptcy",
    arabicTitle: "كتاب 43",
    startHadith: 3235,
    endHadith: 3311,
  ),
  BukhariChapter(
    id: 44,
    englishTitle: "Khusoomaat",
    arabicTitle: "كتاب 44",
    startHadith: 3312,
    endHadith: 3388,
  ),
  BukhariChapter(
    id: 45,
    englishTitle: "Lost Things Picked up by Someone (Luqatah)",
    arabicTitle: "كتاب 45",
    startHadith: 3389,
    endHadith: 3465,
  ),
  BukhariChapter(
    id: 46,
    englishTitle: "Oppressions",
    arabicTitle: "كتاب 46",
    startHadith: 3466,
    endHadith: 3542,
  ),
  BukhariChapter(
    id: 47,
    englishTitle: "Partnership",
    arabicTitle: "كتاب 47",
    startHadith: 3543,
    endHadith: 3619,
  ),
  BukhariChapter(
    id: 48,
    englishTitle: "Mortgaging",
    arabicTitle: "كتاب 48",
    startHadith: 3620,
    endHadith: 3696,
  ),
  BukhariChapter(
    id: 49,
    englishTitle: "Manumission of Slaves",
    arabicTitle: "كتاب 49",
    startHadith: 3697,
    endHadith: 3773,
  ),
  BukhariChapter(
    id: 50,
    englishTitle: "Makaatib",
    arabicTitle: "كتاب 50",
    startHadith: 3774,
    endHadith: 3850,
  ),
  BukhariChapter(
    id: 51,
    englishTitle: "Gifts",
    arabicTitle: "كتاب 51",
    startHadith: 3851,
    endHadith: 3927,
  ),
  BukhariChapter(
    id: 52,
    englishTitle: "Witnesses",
    arabicTitle: "كتاب 52",
    startHadith: 3928,
    endHadith: 4004,
  ),
  BukhariChapter(
    id: 53,
    englishTitle: "Peacemaking",
    arabicTitle: "كتاب 53",
    startHadith: 4005,
    endHadith: 4081,
  ),
  BukhariChapter(
    id: 54,
    englishTitle: "Conditions",
    arabicTitle: "كتاب 54",
    startHadith: 4082,
    endHadith: 4158,
  ),
  BukhariChapter(
    id: 55,
    englishTitle: "Wills and Testaments (Wasaayaa)",
    arabicTitle: "كتاب 55",
    startHadith: 4159,
    endHadith: 4235,
  ),
  BukhariChapter(
    id: 56,
    englishTitle: "Fighting for the Cause of Allah (Jihaad)",
    arabicTitle: "كتاب 56",
    startHadith: 4236,
    endHadith: 4312,
  ),
  BukhariChapter(
    id: 57,
    englishTitle: "One-fifth of Booty to the Cause of Allah (Khumus)",
    arabicTitle: "كتاب 57",
    startHadith: 4313,
    endHadith: 4389,
  ),
  BukhariChapter(
    id: 58,
    englishTitle: "Jizyah and Mawaada'ah",
    arabicTitle: "كتاب 58",
    startHadith: 4390,
    endHadith: 4466,
  ),
  BukhariChapter(
    id: 59,
    englishTitle: "Beginning of Creation",
    arabicTitle: "كتاب 59",
    startHadith: 4467,
    endHadith: 4543,
  ),
  BukhariChapter(
    id: 60,
    englishTitle: "Prophets",
    arabicTitle: "كتاب 60",
    startHadith: 4544,
    endHadith: 4620,
  ),
  BukhariChapter(
    id: 61,
    englishTitle: "Virtues and Merits of the Prophet (pbuh) and his Companions",
    arabicTitle: "كتاب 61",
    startHadith: 4621,
    endHadith: 4697,
  ),
  BukhariChapter(
    id: 62,
    englishTitle: "Companions of the Prophet",
    arabicTitle: "كتاب 62",
    startHadith: 4698,
    endHadith: 4774,
  ),
  BukhariChapter(
    id: 63,
    englishTitle: "Merits of the Helpers in Madinah (Ansaar)",
    arabicTitle: "كتاب 63",
    startHadith: 4775,
    endHadith: 4851,
  ),
  BukhariChapter(
    id: 64,
    englishTitle: "Military Expeditions led by the Prophet (pbuh) (Al-Maghaazi)",
    arabicTitle: "كتاب 64",
    startHadith: 4852,
    endHadith: 4928,
  ),
  BukhariChapter(
    id: 65,
    englishTitle: "Prophetic Commentary on the Qur'an (Tafseer of the Prophet (pbuh))",
    arabicTitle: "كتاب 65",
    startHadith: 4929,
    endHadith: 5005,
  ),
  BukhariChapter(
    id: 66,
    englishTitle: "Virtues of the Qur'an",
    arabicTitle: "كتاب 66",
    startHadith: 5006,
    endHadith: 5082,
  ),
  BukhariChapter(
    id: 67,
    englishTitle: "Wedlock, Marriage (Nikaah)",
    arabicTitle: "كتاب 67",
    startHadith: 5083,
    endHadith: 5159,
  ),
  BukhariChapter(
    id: 68,
    englishTitle: "Divorce",
    arabicTitle: "كتاب 68",
    startHadith: 5160,
    endHadith: 5236,
  ),
  BukhariChapter(
    id: 69,
    englishTitle: "Supporting the Family",
    arabicTitle: "كتاب 69",
    startHadith: 5237,
    endHadith: 5313,
  ),
  BukhariChapter(
    id: 70,
    englishTitle: "Food, Meals",
    arabicTitle: "كتاب 70",
    startHadith: 5314,
    endHadith: 5390,
  ),
  BukhariChapter(
    id: 71,
    englishTitle: "Sacrifice on Occasion of Birth (`Aqiqa)",
    arabicTitle: "كتاب 71",
    startHadith: 5391,
    endHadith: 5467,
  ),
  BukhariChapter(
    id: 72,
    englishTitle: "Hunting, Slaughtering",
    arabicTitle: "كتاب 72",
    startHadith: 5468,
    endHadith: 5544,
  ),
  BukhariChapter(
    id: 73,
    englishTitle: "Al-Adha Festival Sacrifice (Adaahi)",
    arabicTitle: "كتاب 73",
    startHadith: 5545,
    endHadith: 5621,
  ),
  BukhariChapter(
    id: 74,
    englishTitle: "Drinks",
    arabicTitle: "كتاب 74",
    startHadith: 5622,
    endHadith: 5698,
  ),
  BukhariChapter(
    id: 75,
    englishTitle: "Patients",
    arabicTitle: "كتاب 75",
    startHadith: 5699,
    endHadith: 5775,
  ),
  BukhariChapter(
    id: 76,
    englishTitle: "Medicine",
    arabicTitle: "كتاب 76",
    startHadith: 5776,
    endHadith: 5852,
  ),
  BukhariChapter(
    id: 77,
    englishTitle: "Dress",
    arabicTitle: "كتاب 77",
    startHadith: 5853,
    endHadith: 5929,
  ),
  BukhariChapter(
    id: 78,
    englishTitle: "Good Manners and Form (Al-Adab)",
    arabicTitle: "كتاب 78",
    startHadith: 5930,
    endHadith: 6006,
  ),
  BukhariChapter(
    id: 79,
    englishTitle: "Asking Permission",
    arabicTitle: "كتاب 79",
    startHadith: 6007,
    endHadith: 6083,
  ),
  BukhariChapter(
    id: 80,
    englishTitle: "Invocations",
    arabicTitle: "كتاب 80",
    startHadith: 6084,
    endHadith: 6160,
  ),
  BukhariChapter(
    id: 81,
    englishTitle: "To make the Heart Tender (Ar-Riqaq)",
    arabicTitle: "كتاب 81",
    startHadith: 6161,
    endHadith: 6237,
  ),
  BukhariChapter(
    id: 82,
    englishTitle: "Divine Will (Al-Qadar)",
    arabicTitle: "كتاب 82",
    startHadith: 6238,
    endHadith: 6314,
  ),
  BukhariChapter(
    id: 83,
    englishTitle: "Oaths and Vows",
    arabicTitle: "كتاب 83",
    startHadith: 6315,
    endHadith: 6391,
  ),
  BukhariChapter(
    id: 84,
    englishTitle: "Expiation for Unfulfilled Oaths",
    arabicTitle: "كتاب 84",
    startHadith: 6392,
    endHadith: 6468,
  ),
  BukhariChapter(
    id: 85,
    englishTitle: "Laws of Inheritance (Al-Faraa'id)",
    arabicTitle: "كتاب 85",
    startHadith: 6469,
    endHadith: 6545,
  ),
  BukhariChapter(
    id: 86,
    englishTitle: "Limits and Punishments set by Allah (Hudood)",
    arabicTitle: "كتاب 86",
    startHadith: 6546,
    endHadith: 6622,
  ),
  BukhariChapter(
    id: 87,
    englishTitle: "Blood Money (Ad-Diyat)",
    arabicTitle: "كتاب 87",
    startHadith: 6623,
    endHadith: 6699,
  ),
  BukhariChapter(
    id: 88,
    englishTitle: "Apostates",
    arabicTitle: "كتاب 88",
    startHadith: 6700,
    endHadith: 6776,
  ),
  BukhariChapter(
    id: 89,
    englishTitle: "(Statements made under) Coercion",
    arabicTitle: "كتاب 89",
    startHadith: 6777,
    endHadith: 6853,
  ),
  BukhariChapter(
    id: 90,
    englishTitle: "Tricks",
    arabicTitle: "كتاب 90",
    startHadith: 6854,
    endHadith: 6930,
  ),
  BukhariChapter(
    id: 91,
    englishTitle: "Interpretation of Dreams",
    arabicTitle: "كتاب 91",
    startHadith: 6931,
    endHadith: 7007,
  ),
  BukhariChapter(
    id: 92,
    englishTitle: "Afflictions and the End of the World",
    arabicTitle: "كتاب 92",
    startHadith: 7008,
    endHadith: 7084,
  ),
  BukhariChapter(
    id: 93,
    englishTitle: "Judgments (Ahkaam)",
    arabicTitle: "كتاب 93",
    startHadith: 7085,
    endHadith: 7161,
  ),
  BukhariChapter(
    id: 94,
    englishTitle: "Wishes",
    arabicTitle: "كتاب 94",
    startHadith: 7162,
    endHadith: 7238,
  ),
  BukhariChapter(
    id: 95,
    englishTitle: "Accepting Information Given by a Truthful Person",
    arabicTitle: "كتاب 95",
    startHadith: 7239,
    endHadith: 7315,
  ),
  BukhariChapter(
    id: 96,
    englishTitle: "Holding Fast to the Qur'an and Sunnah",
    arabicTitle: "كتاب 96",
    startHadith: 7316,
    endHadith: 7392,
  ),
  BukhariChapter(
    id: 97,
    englishTitle: "Oneness, Uniqueness of Allah (Tawheed)",
    arabicTitle: "كتاب 97",
    startHadith: 7393,
    endHadith: 7589,
  ),
];
