// Fichier généré automatiquement contenant les chapitres de Sahih Muslim
// Généré le 2025-04-11T21:45:49.028815

import 'package:salaty/models/hadith_chapter.dart';

// Liste des chapitres de Sahih Muslim
final List<HadithChapter> muslimChaptersData = [
  HadithChapter(
    chapterNumber: "0",
    title: "Introduction",
    titleArabic: "كتاب 0",
    collectionId: "muslim",
    hadithCount: 92,
  ),
  HadithChapter(
    chapterNumber: "1",
    title: "The Book of Faith",
    titleArabic: "كتاب 1",
    collectionId: "muslim",
    hadithCount: 441,
  ),
  HadithChapter(
    chapterNumber: "2",
    title: "The Book of Purification",
    titleArabic: "كتاب 2",
    collectionId: "muslim",
    hadithCount: 145,
  ),
  HadithChapter(
    chapterNumber: "3",
    title: "The Book of Menstruation",
    titleArabic: "كتاب 3",
    collectionId: "muslim",
    hadithCount: 158,
  ),
  HadithChapter(
    chapterNumber: "4",
    title: "The Book of Prayers",
    titleArabic: "كتاب 4",
    collectionId: "muslim",
    hadithCount: 324,
  ),
  HadithChapter(
    chapterNumber: "5",
    title: "The Book of Mosques and Places of Prayer",
    titleArabic: "كتاب 5",
    collectionId: "muslim",
    hadithCount: 409,
  ),
  HadithChapter(
    chapterNumber: "6",
    title: "The Book of Prayer - Travellers",
    titleArabic: "كتاب 6",
    collectionId: "muslim",
    hadithCount: 381,
  ),
  HadithChapter(
    chapterNumber: "7",
    title: "The Book of Prayer - Friday",
    titleArabic: "كتاب 7",
    collectionId: "muslim",
    hadithCount: 93,
  ),
  HadithChapter(
    chapterNumber: "8",
    title: "The Book of Prayer - Two Eids",
    titleArabic: "كتاب 8",
    collectionId: "muslim",
    hadithCount: 26,
  ),
  HadithChapter(
    chapterNumber: "9",
    title: "The Book of Prayer - Rain",
    titleArabic: "كتاب 9",
    collectionId: "muslim",
    hadithCount: 19,
  ),
  HadithChapter(
    chapterNumber: "10",
    title: "The Book of Prayer - Eclipses",
    titleArabic: "كتاب 10",
    collectionId: "muslim",
    hadithCount: 34,
  ),
  HadithChapter(
    chapterNumber: "11",
    title: "The Book of Prayer - Funerals",
    titleArabic: "كتاب 11",
    collectionId: "muslim",
    hadithCount: 140,
  ),
  HadithChapter(
    chapterNumber: "12",
    title: "The Book of Zakat",
    titleArabic: "كتاب 12",
    collectionId: "muslim",
    hadithCount: 232,
  ),
  HadithChapter(
    chapterNumber: "13",
    title: "The Book of Fasting",
    titleArabic: "كتاب 13",
    collectionId: "muslim",
    hadithCount: 285,
  ),
  HadithChapter(
    chapterNumber: "14",
    title: "The Book of I\'tikaf",
    titleArabic: "كتاب 14",
    collectionId: "muslim",
    hadithCount: 11,
  ),
  HadithChapter(
    chapterNumber: "15",
    title: "The Book of Pilgrimage",
    titleArabic: "كتاب 15",
    collectionId: "muslim",
    hadithCount: 607,
  ),
  HadithChapter(
    chapterNumber: "16",
    title: "The Book of Marriage",
    titleArabic: "كتاب 16",
    collectionId: "muslim",
    hadithCount: 3180,
  ),
  HadithChapter(
    chapterNumber: "17",
    title: "The Book of Suckling",
    titleArabic: "كتاب 17",
    collectionId: "muslim",
    hadithCount: 84,
  ),
  HadithChapter(
    chapterNumber: "18",
    title: "The Book of Divorce",
    titleArabic: "كتاب 18",
    collectionId: "muslim",
    hadithCount: 91,
  ),
  HadithChapter(
    chapterNumber: "19",
    title: "The Book of Invoking Curses",
    titleArabic: "كتاب 19",
    collectionId: "muslim",
    hadithCount: 27,
  ),
  HadithChapter(
    chapterNumber: "20",
    title: "The Book of Emancipating Slaves",
    titleArabic: "كتاب 20",
    collectionId: "muslim",
    hadithCount: 31,
  ),
  HadithChapter(
    chapterNumber: "21",
    title: "The Book of Transactions",
    titleArabic: "كتاب 21",
    collectionId: "muslim",
    hadithCount: 161,
  ),
  HadithChapter(
    chapterNumber: "22",
    title: "The Book of Musaqah",
    titleArabic: "كتاب 22",
    collectionId: "muslim",
    hadithCount: 178,
  ),
  HadithChapter(
    chapterNumber: "23",
    title: "The Book of the Rules of Inheritance",
    titleArabic: "كتاب 23",
    collectionId: "muslim",
    hadithCount: 23,
  ),
  HadithChapter(
    chapterNumber: "24",
    title: "The Book of Gifts",
    titleArabic: "كتاب 24",
    collectionId: "muslim",
    hadithCount: 41,
  ),
  HadithChapter(
    chapterNumber: "25",
    title: "The Book of Wills",
    titleArabic: "كتاب 25",
    collectionId: "muslim",
    hadithCount: 31,
  ),
  HadithChapter(
    chapterNumber: "26",
    title: "The Book of Vows",
    titleArabic: "كتاب 26",
    collectionId: "muslim",
    hadithCount: 19,
  ),
  HadithChapter(
    chapterNumber: "27",
    title: "The Book of Oaths",
    titleArabic: "كتاب 27",
    collectionId: "muslim",
    hadithCount: 88,
  ),
  HadithChapter(
    chapterNumber: "28",
    title: "The Book of Oaths, Muharibin, Qasas (Retaliation), and Diyat (Blood Money)",
    titleArabic: "كتاب 28",
    collectionId: "muslim",
    hadithCount: 56,
  ),
  HadithChapter(
    chapterNumber: "29",
    title: "The Book of Legal Punishments",
    titleArabic: "كتاب 29",
    collectionId: "muslim",
    hadithCount: 72,
  ),
  HadithChapter(
    chapterNumber: "30",
    title: "The Book of Judicial Decisions",
    titleArabic: "كتاب 30",
    collectionId: "muslim",
    hadithCount: 28,
  ),
  HadithChapter(
    chapterNumber: "31",
    title: "The Book of Lost Property",
    titleArabic: "كتاب 31",
    collectionId: "muslim",
    hadithCount: 21,
  ),
  HadithChapter(
    chapterNumber: "32",
    title: "The Book of Jihad and Expeditions",
    titleArabic: "كتاب 32",
    collectionId: "muslim",
    hadithCount: 182,
  ),
  HadithChapter(
    chapterNumber: "33",
    title: "The Book on Government",
    titleArabic: "كتاب 33",
    collectionId: "muslim",
    hadithCount: 267,
  ),
  HadithChapter(
    chapterNumber: "34",
    title: "The Book of Hunting, Slaughter, and what may be Eaten",
    titleArabic: "كتاب 34",
    collectionId: "muslim",
    hadithCount: 92,
  ),
  HadithChapter(
    chapterNumber: "35",
    title: "The Book of Sacrifices",
    titleArabic: "كتاب 35",
    collectionId: "muslim",
    hadithCount: 63,
  ),
  HadithChapter(
    chapterNumber: "36",
    title: "The Book of Drinks",
    titleArabic: "كتاب 36",
    collectionId: "muslim",
    hadithCount: 270,
  ),
  HadithChapter(
    chapterNumber: "37",
    title: "The Book of Clothes and Adornment",
    titleArabic: "كتاب 37",
    collectionId: "muslim",
    hadithCount: 201,
  ),
  HadithChapter(
    chapterNumber: "38",
    title: "The Book of Manners and Etiquette",
    titleArabic: "كتاب 38",
    collectionId: "muslim",
    hadithCount: 60,
  ),
  HadithChapter(
    chapterNumber: "39",
    title: "The Book of Greetings",
    titleArabic: "كتاب 39",
    collectionId: "muslim",
    hadithCount: 216,
  ),
  HadithChapter(
    chapterNumber: "40",
    title: "The Book Concerning the Use of Correct Words",
    titleArabic: "كتاب 40",
    collectionId: "muslim",
    hadithCount: 23,
  ),
  HadithChapter(
    chapterNumber: "41",
    title: "The Book of Poetry",
    titleArabic: "كتاب 41",
    collectionId: "muslim",
    hadithCount: 10,
  ),
  HadithChapter(
    chapterNumber: "42",
    title: "The Book of Dreams",
    titleArabic: "كتاب 42",
    collectionId: "muslim",
    hadithCount: 41,
  ),
  HadithChapter(
    chapterNumber: "43",
    title: "The Book of Virtues",
    titleArabic: "كتاب 43",
    collectionId: "muslim",
    hadithCount: 5785,
  ),
  HadithChapter(
    chapterNumber: "44",
    title: "The Book of the Merits of the Companions",
    titleArabic: "كتاب 44",
    collectionId: "muslim",
    hadithCount: 331,
  ),
  HadithChapter(
    chapterNumber: "45",
    title: "The Book of Virtue, Enjoining Good Manners, and Joining of the Ties of Kinship",
    titleArabic: "كتاب 45",
    collectionId: "muslim",
    hadithCount: 223,
  ),
  HadithChapter(
    chapterNumber: "46",
    title: "The Book of Destiny",
    titleArabic: "كتاب 46",
    collectionId: "muslim",
    hadithCount: 52,
  ),
  HadithChapter(
    chapterNumber: "47",
    title: "The Book of Knowledge",
    titleArabic: "كتاب 47",
    collectionId: "muslim",
    hadithCount: 30,
  ),
  HadithChapter(
    chapterNumber: "48",
    title: "The Book Pertaining to the Remembrance of Allah, Supplication, Repentance and Seeking Forgiveness",
    titleArabic: "كتاب 48",
    collectionId: "muslim",
    hadithCount: 132,
  ),
  HadithChapter(
    chapterNumber: "49",
    title: "The Book of Heart-Melting Traditions",
    titleArabic: "كتاب 49",
    collectionId: "muslim",
    hadithCount: 15,
  ),
  HadithChapter(
    chapterNumber: "50",
    title: "The Book of Repentance",
    titleArabic: "كتاب 50",
    collectionId: "muslim",
    hadithCount: 72,
  ),
  HadithChapter(
    chapterNumber: "51",
    title: "Characteristics of The Hypocrites And Rulings Concerning Them",
    titleArabic: "كتاب 51",
    collectionId: "muslim",
    hadithCount: 21,
  ),
  HadithChapter(
    chapterNumber: "52",
    title: "Characteristics of the Day of Judgment, Paradise, and Hell",
    titleArabic: "كتاب 52",
    collectionId: "muslim",
    hadithCount: 85,
  ),
  HadithChapter(
    chapterNumber: "53",
    title: "The Book of Paradise, its Description, its Bounties and its Inhabitants",
    titleArabic: "كتاب 53",
    collectionId: "muslim",
    hadithCount: 105,
  ),
  HadithChapter(
    chapterNumber: "54",
    title: "The Book of Tribulations and Portents of the Last Hour",
    titleArabic: "كتاب 54",
    collectionId: "muslim",
    hadithCount: 182,
  ),
  HadithChapter(
    chapterNumber: "55",
    title: "The Book of Zuhd and Softening of Hearts",
    titleArabic: "كتاب 55",
    collectionId: "muslim",
    hadithCount: 106,
  ),
  HadithChapter(
    chapterNumber: "56",
    title: "The Book of Commentary on the Qur\'an",
    titleArabic: "كتاب 56",
    collectionId: "muslim",
    hadithCount: 41,
  ),
];
